app/app/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'app.views.home', name='home'),
    # url(r'^app/', include('app.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

apps/locks/urls.py
# coding: utf-8
from django.conf.urls import patterns, url, include

urlpatterns = patterns('locks.views',
    url(r'^$', 'index', name='index'),
    url(r'^create/$', 'create', name='create'),
    url(r'^delete_file/(\d+)/$', 'delete_file', name='delete_file'),
    url(r'^unlock_file/(\d+)/$', 'unlock_file', name='unlock_file'),
)

apps/urls.py
from django.conf import settings
import re
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^twauthorizer/', include('twauthorizer.urls', namespace='twauthorizer')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^locks/', include('locks.urls', namespace='locks')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('core.urls', namespace='core')),
)

if settings.WEB_SERVER == 'development':
    urlpatterns += patterns('',
        (
            ur'^%s(?P<path>.*)$' % re.sub(ur'^/', u'', settings.MEDIA_URL),
            'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT}
        ),
    )

core/core/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'core.views.home', name='home'),
    # url(r'^core/', include('core.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

apps/locks/models.py
# coding: utf-8
from django.conf import settings
import re
import datetime
from django.core.files import File
from django.utils.crypto import get_random_string
from django.utils.timezone import now as django_now
from django.db import models
from accounts.models import UserProfile
from locks.filelocker import FileLocker


class LockManager(models.Manager):

    def create_by_user(self, user, uploaded_file, period, saved_hours):
        locked_at = django_now()
        unlockable_at = locked_at + datetime.timedelta(days=period)

        max_saved_hours = period * 24
        if saved_hours > max_saved_hours:
            saved_hours = max_saved_hours

        password = get_random_string(8, allowed_chars='0123456789')
        fl = FileLocker()
        fl.lock(uploaded_file, password)
        locked_file = File(
            open(fl.get_locked_file_path(), 'r'),
            name=fl.get_locked_file_name()
        )

        obj = self.create(
            user_profile=user.get_profile(),
            locked_file=locked_file,
            locked_file_name=fl.get_locked_file_name(),
            original_file_name=uploaded_file.name,
            original_file_size=uploaded_file.size,
            password=password,
            locked_at=locked_at,
            unlockable_at=unlockable_at,
            saved_hours=saved_hours
        )

        locked_file.close()
        fl.clean()
        return obj

    def sum_saved_hours(self, period=None):
        u'''period is number of days from now to the past
          for including aggregation'''
        qs = self.all()
        if period is not None:
            now = django_now()
            in_period = now - datetime.timedelta(days=period)
            qs = qs.filter(locked_at__gt=in_period)
        result = qs.aggregate(models.Sum('saved_hours'))
        return result['saved_hours__sum'] or 0


def _locked_file_upload_to(instance, filename):
    now = django_now()
    return '%s/%04d/%02d/%s/%s' % (
        settings.LOCKED_FILES_DIR_NAME,
        now.year,
        now.month,
        get_random_string(32),
        filename,
    )


class Lock(models.Model):
    objects = LockManager()
    user_profile = models.ForeignKey(UserProfile, related_name='lock_set')
    locked_file = models.FileField(upload_to=_locked_file_upload_to)
    locked_file_name = models.CharField(max_length=255)
    original_file_name = models.CharField(max_length=255)
    original_file_size = models.PositiveIntegerField()
    password = models.CharField(max_length=16)
    locked_at = models.DateTimeField(help_text=u'施錠日時')
    unlockable_at = models.DateTimeField(help_text=u'解錠可能日時')
    unlocked_at = models.DateTimeField(
        blank=True, null=True, help_text=u'解錠日時')
    saved_hours = models.PositiveIntegerField()

    def __unicode__(self):
        return u'%s' % (self.original_file_name,)

    class Meta:
        db_table = 'locks_lock'
        verbose_name = 'Lock'
        verbose_name_plural = 'Locks'

    def is_unlockable(self):
        return django_now() > self.unlockable_at

    def delete_locked_file(self):
        self.locked_file.delete()

    def unlock_locked_file(self):
        self.unlocked_at = django_now()
        self.save()

apps/locks/forms.py
# coding: utf-8
from django.conf import settings
import re
from django import forms
from django.forms import widgets


class LockedFileField(forms.FileField):

    def __init__(self):
        super(self.__class__, self).__init__()
        self._max_file_size = settings.MAX_LOCKED_FILE_SIZE
        self._max_file_name_length = settings.MAX_LOCKED_FILE_NAME_LENGTH

    def clean(self, value, initial):
        if value is None:
            raise forms.ValidationError('Empty file')

        if value.size > self._max_file_size:
            raise forms.ValidationError('Over file size')
        if len(value.name) > self._max_file_name_length:
            raise forms.ValidationError('Over file name length')

        return value


class CreateForm(forms.Form):

    locked_file = LockedFileField()
    period = forms.IntegerField(
        min_value=1, max_value=30, initial=7)
    saved_hours = forms.IntegerField(
        min_value=1, max_value=30 * 24, initial=7)

    #def clean(self):
    #    if self._errors:
    #        return

    #    # TODO:
    #    # - 最大save_hoursは日数 * 24で切り捨てる

    #    return self.cleaned_data

apps/locks/views.py
# coding: utf-8
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.db.transaction import commit_on_success
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.template.loader import get_template
from locks.forms import CreateForm
from locks.models import Lock


@login_required
def index(request):
    c = {
        'locks': Lock.objects.filter(
            user_profile=request.user.get_profile()).order_by('-locked_at'),
    }
    return render_to_response('locks/index.html', c,
        context_instance=RequestContext(request))


@login_required
@commit_on_success
def create(request):
    if request.method == 'POST':
        form = CreateForm(request.POST, request.FILES)
        if form.is_valid():
            Lock.objects.create_by_user(
                request.user,
                form.cleaned_data['locked_file'],
                form.cleaned_data['period'],
                form.cleaned_data['saved_hours'],
            )
            return HttpResponseRedirect(reverse('locks:index'))
    else:
        form = CreateForm()

    c = dict(form=form)
    return render_to_response('locks/create.html', c,
        context_instance=RequestContext(request))


@login_required
@commit_on_success
def delete_file(request, id):
    Lock.objects.get(id=id).delete_locked_file()
    return HttpResponseRedirect(reverse('locks:index'))


@login_required
@commit_on_success
def unlock_file(request, id):
    Lock.objects.get(id=id).unlock_locked_file()
    return HttpResponseRedirect(reverse('locks:index'))

templates/locks/create.html
{% extends "base.html" %}
{% load url from future %}

{% block nav_locks_class %}active{% endblock %}

{% block page_body %}
<h1>Lock your file</h1>
<form action="{% url 'locks:create' %}" method="post"
  enctype="multipart/form-data">
  {% csrf_token %}
  {{form.as_p}}
  <p><input id="_submit" type="submit" value="Submit"></p>
  <script>
    $a.attachConfirmation('_submit', 'OK?', 'Please wait for upload finish');
  </script>
</form>
{% endblock %}

templates/locks/index.html
{% extends "base.html" %}
{% load url from future %}

{% block nav_locks_class %}active{% endblock %}

{% block page_body %}
<h1>Your locks</h1>

<div style="margin-top:20px;">
  <a href="{% url 'locks:create' %}" class="btn btn-large btn-primary">Lock your file</a>
</div>

{% if locks %}
<table class="table" style="margin-top:20px;">
  <tr>
    <th>Original file name</th>
    <th>Locked file</th>
    <th>Locked at</th>
    <th>Until unlockable</th>
    <th>Saved hours</th>
  </tr>
{% for lock in locks %}
  <tr>
    <td>{{lock.original_file_name}}</td>
    <td>
    {% if lock.locked_file %}
      <a href="{{lock.locked_file.url}}">{{lock.locked_file_name}}</a><br />
      [<a id="delete_file-{{lock.id}}" href="{% url 'locks:delete_file' lock.id %}">Delete file</a>]
      <script>
        $a.attachConfirmation('delete_file-{{lock.id}}', 'Are you sure you want it?');
      </script>
    {% else %}
      <span class="inactive">{{lock.locked_file_name}}</span>
    {% endif %}
    </td>
    <td>{{lock.locked_at|date:"Y/m/d"}}<br />{{lock.locked_at|time:"H:i:s"}}</td>
    <td>
    {% if lock.is_unlockable %}
      {% if lock.unlocked_at %}
        Password:<br />
        [{{lock.password}}]
      {% else %}
        [<a id="unlock_file-{{lock.id}}" href="{% url 'locks:unlock_file' lock.id %}">Unlock</a>]
        <script>
          $a.attachConfirmation(
            'unlock_file-{{lock.id}}',
            'Are you sure you want it?\nRecollect a reason that you used this site!'
          );
        </script>
      {% endif %}
    {% else %}
      {{lock.unlockable_at|timeuntil}}
    {% endif %}
    </td>
    <td>+{{lock.saved_hours}}</td>
  </tr>
{% endfor %}
</table>
{% endif %}

{% endblock %}