app/app/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'app.views.home', name='home'),
    # url(r'^app/', include('app.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

apps/core/urls.py
# coding: utf-8
from django.conf.urls import patterns, url, include

urlpatterns = patterns('core.views',
    url(r'^$', 'index', name='index'),
)

apps/twauthorizer/urls.py
# coding: utf-8
from django.conf.urls import patterns, url, include

urlpatterns = patterns('twauthorizer.views',
    url(r'^auth/$', 'auth', name='auth'),
    url(r'^auth_callback/$', 'auth_callback', name='auth_callback'),
)

apps/urls.py
from django.conf import settings
import re
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^twauthorizer/', include('twauthorizer.urls', namespace='twauthorizer')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^locks/', include('locks.urls', namespace='locks')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('core.urls', namespace='core')),
)

if settings.WEB_SERVER == 'development':
    urlpatterns += patterns('',
        (
            ur'^%s(?P<path>.*)$' % re.sub(ur'^/', u'', settings.MEDIA_URL),
            'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT}
        ),
    )

core/core/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'core.views.home', name='home'),
    # url(r'^core/', include('core.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

apps/core/models.py
from django.db import models

apps/core/views.py
# coding: utf-8
from django.conf import settings
from django.db.transaction import commit_on_success
from django.http import HttpResponse
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.template.loader import get_template
from django.views.decorators.csrf import csrf_exempt
from locks.models import Lock


def index(request):
    c = {
        'total_saved_hours': Lock.objects.sum_saved_hours(),
        'today_saved_hours': Lock.objects.sum_saved_hours(period=1)
    }
    return render_to_response('core/index.html', c,
        context_instance=RequestContext(request))

templates/core/index.html
{% extends "base.html" %}
{% load url from future %}

{% block nav_home_class %}active{% endblock %}

{% block page_body %}
<div class="jumbotron">
  <h1>Do you enjoy playing the game really?</h1>
  <p class="lead">A gameplay is very funny .. if you have enough time for the playing.<br />
  This service will lock your game until you have to finish a homework.</p>
  <a class="btn btn-large btn-primary" href="{% url 'twauthorizer:auth' %}">Stop your unhappy game life</a>
</div>

<hr>

<p class="lead" style="text-align:center;">We saved <strong class="text-success">
  {{total_saved_hours}}</strong> hours (today <strong class="text-success">+{{today_saved_hours}}</strong> hours)
</p>

<hr>

<h2>How to use</h2>
<div class="row-fluid">
  <div class="span4">
    <h4>1. Upload your game file</h4>
    <p>
      Upload your game file along with the period that you want to stop it.<br />
      You must archive it in advance, If the target is folder.<br />
      <small class="text-info">Note: Max size for upload file is
        <strong>{{MAX_LOCKED_FILE_SIZE|filesizeformat}}</strong>.</small>
    </p>
  </div>
  <div class="span4">
    <h4>2. Download locked your file</h4>
    <p>
      The uploaded file will be compressed to passworded zip at once.<br />
      It must  be downloaded in your PC.<br />
      <small class="text-info">Note: You can to delete the locked file in server.</small>
    </p>
  </div>
  <div class="span4">
    <h4>3. Delete original file</h4>
    <p>
      Delete or move far your original file.<br />
      When the your set period comes, this site will display password for unlocking file.<br />
      Let's enjoy a happy game life!
    </p>
  </div>
</div>

<hr>

<h2>Examples of the utility</h2>
<div class="row-fluid">
  <div class="span6">
    <h4>General consumer games</h4>
    <p>
      General consumer games will have huge file size, and also they needs to install into your PC.<br />
      In such a case, you should upload only save game data.<br />
    </p>
  </div>
  <div class="span6">
    <h4>Rogue-like games</h4>
    <p>
      Almost Rogue-like games are small file size, and they are not necessary to install.
      (e.g.
        <a href="http://www.dungeoncrawl.org/" target="_blank">Dungeon Crawl</a>,
        <a href="http://rephial.org/" target="_blank">Angband</a>,
        <a href="http://www.nethack.org/" target="_blank">NetHack</a>,
        <a href="http://hengband.sourceforge.jp/" target="_blank">Hengband</a>,
        <a href="http://homepage3.nifty.com/rfish/elona_top.html" target="_blank">Elona</a>,
      ..)<br />
      The good method of that case, you compress the game folder to ZIP,
        and then you upload whole the compressed file.
    </p>
  </div>
</div>
{% endblock %}